### ISSUE TITLE
YouTube Video Not Stopping When Closing Popup

### ISSUE THREAD

**Issue by krishanthan4** [PatrikFehrenbach/practical-bug-bounty#6]
## YouTube Video Not Stopping When Closing Popup

**Issue Description:**
When a user is playing a video and closes the popup, the video continues to play in the background. This behavior forces the user to return to the video manually and stop it. This interrupts the user experience and can be frustrating.

**Expected Behavior:**
If the user clicks the close button on the popup, the video should stop playing immediately. This will enhance user convenience and ensure a seamless experience when interacting with the platform.

**Steps to Reproduce:**
1. Open the application and play a video.
2. Close the popup containing the video while it's playing.
3. Observe that the video continues to play even after the popup is closed.

**Screenshots/Attachments:**
![Pasted image 20231010102323](https://github.com/PatrikFehrenbach/practical-bug-bounty/assets/122454062/ff6d1a02-19bc-4a4a-93aa-436dc3883f7a)

**Additional Information:**
- Operating System: [e.g., Windows 10,Linux Mint 21.2]
- Browser and Version: [Brave Version 1.57.62 ]
- Device: [Desktop, Laptop,]

**Note:** This issue affects the user experience negatively and should be prioritized for resolution.

**Comment by PatrikFehrenbach** [comment]
Hey @krishanthan4 

Thank you very much! I have implemented a Fix to address this: 

```
<script>
    $(document).ready(function(){
        $('.modal').on('hidden.bs.modal', function (e) {
            var iframe = $(this).find('iframe');
            
            iframe.attr('src', iframe.attr('src'));
        });
    });
</script>
``` 

The changes should be live on https://practicalbugbounty.com/ already, please let me know if this fixed it.

**Comment by krishanthan4** [comment]
Thanks @PatrikFehrenbach . The issue has not occurred again. Appreciate your swift action!, 
By the way Currently I'm making a Chapters list to the platform.After I completed it ,I will send it withing today.
